#!/bin/bash -l
source $HOME/.bashrc
cd $PBS_O_WORKDIR
param1=$1
destnode=`uname -n`
hh=`hostname`
echo "destnode is = [$destnode] PARAM1=$1 hostname=$hh. Vnode = $PBS_VNODENUM"
#echo "My vnodenum = "
source /mnt/lustre/users/mnasir/nas-llm/bin/activate
#export TRANSFORMERS_CACHE=/mnt/lustre/users/mnasir/NAS-LLM/.chache/huggingface
ray start --address="${param1}" --redis-password='5241590000000000'
#echo `ps -aux | grep -i ray`
#echo $?
#echo "sleeping"
#sleep 10
#echo "Slept"
#echo "========================"

#echo `ps -aux | grep -i ray`
#echo "============================================"
#ray status


#echo "Sleeping lots now"


#sleep 300

WALLTIME=$(qstat -f $PBS_JOBID | sed -rn 's/.*Resource_List.walltime = (.*)/\1/p')

SECONDS=`echo $WALLTIME | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }'`
SECONDS=$((SECONDS*15))
echo "SLEEPING FOR $SECONDS s"
sleep $SECONDS
